version: '3.8'

services:
 db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: salas-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
