version: '3.8'

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Porta AMQP
      - "15672:15672" # Interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - classroom-network

  # Banco de dados para ms-user
  db-user:
    image: postgres:14-alpine
    container_name: db-user
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msuser
    volumes:
      - db_user_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  # Banco de dados para salas-service
  db-salas:
    image: postgres:14-alpine
    container_name: db-salas
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salas
    volumes:
      - db_salas_data:/var/lib/postgresql/data
    networks:
      - classroom-network

volumes:
  rabbitmq_data:
  db_user_data:
  db_salas_data:

networks:
  classroom-network:
    driver: bridge